language: csharp
mono: none
dotnet: 2.1.402

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode10

install:
  - dotnet restore RealTimePassengerInformation/RealTimePassengerInformation.fsproj
  - dotnet restore RealTimePassengerInformation.UnitTests/RealTimePassengerInformation.UnitTests.fsproj
script:
  - dotnet build RealTimePassengerInformation/RealTimePassengerInformation.fsproj --no-restore /p:Configuration=Debug
  - dotnet build RealTimePassengerInformation/RealTimePassengerInformation.fsproj --no-restore /p:Configuration=Release
  - dotnet build RealTimePassengerInformation.UnitTests/RealTimePassengerInformation.UnitTests.fsproj --no-restore /p:Configuration=Debug
  - dotnet test RealTimePassengerInformation.UnitTests/RealTimePassengerInformation.UnitTests.fsproj --no-restore --no-build /p:Configuration=Debug
