language: csharp
mono: none
dotnet: 2.1.402
install:
  - dotnet restore
script:
  - dotnet build RealTimePassengerInformation/RealTimePassengerInformation.fsproj /p:Configuration=Release
  - dotnet test RealTimePassengerInformation.UnitTests/RealTimePassengerInformation.UnitTests.fsproj /p:Configuration=Release
