version: '0.0.{build}'
image:
  - Visual Studio 2017
branches:
  only:
  - master
deploy: off
init:
install:
dotnet_csproj:
  patch: true
  file: '**\*.fsproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - cmd: dotnet restore RealTimePassengerInformation/RealTimePassengerInformation.fsproj
build_script:
  - cmd: dotnet build RealTimePassengerInformation/RealTimePassengerInformation.fsproj /p:Configuration=Release
after_build:
before_test:
  - cmd: dotnet restore RealTimePassengerInformation.UnitTests/RealTimePassengerInformation.UnitTests.fsproj
  - cmd: nuget install xunit.runner.console -Version 2.4.0 -OutputDirectory tools
  - cmd: nuget install xunit.extensibility.execution -Version 2.4.0 -OutputDirectory %userprofile%\.nuget\packages
  - cmd: nuget install opencover -Version 4.6.519 -OutputDirectory tools
test_script:
  - cmd: dotnet test RealTimePassengerInformation.UnitTests/RealTimePassengerInformation.UnitTests.fsproj /p:Configuration=Release
  - cmd: .\tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:dotnet.exe "-targetargs:"".\tools\xunit.runner.console.2.4.0\tools\netcoreapp2.0\xunit.console.dll"" ""RealTimePassengerInformation.UnitTests\bin\Release\netcoreapp2.1\RealTimePassengerInformation.UnitTests.dll"" -noshadow -appveyor" -oldStyle -output:".\coverage.xml" -filter:"+[RealTimePassengerInformation]*"
after_test:
  - ps: |
      $env:PATH='C:\msys64\usr\bin;'+$env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml"
artifacts:
before_deploy:
after_deploy:
on_success:
on_failure:
on_finish:
